pipeline {
    agent any

    stages {
        // Build
        stage('Build') {
            steps {
                sh 'chmod +x ./jenkins/scripts/build.sh && ./jenkins/scripts/build.sh'
            }
        }
        // Deploy
        stage('Deploy') {
            when {
                branch 'master'
            }
            steps {
                sh 'chmod +x ./jenkins/scripts/deploy.sh && ./jenkins/scripts/deploy.sh'
            }
        }
    }
}
